// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcY5bhTK6WoV2mYoMoqJJFe8abTOipM-E',
    appId: '1:641995843071:web:35f8296dfc586662c9b3ca',
    messagingSenderId: '641995843071',
    projectId: 'mental-health-care-82015',
    authDomain: 'mental-health-care-82015.firebaseapp.com',
    storageBucket: 'mental-health-care-82015.firebasestorage.app',
    measurementId: 'G-RM7JE9M5ST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4xPodli9tAqrbZUAwcDQaRoOxzILCEL8',
    appId: '1:641995843071:android:6eb5c93c7d05e567c9b3ca',
    messagingSenderId: '641995843071',
    projectId: 'mental-health-care-82015',
    storageBucket: 'mental-health-care-82015.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiE5it8w3rSg6GdWfWFQP7dzFO7-G0E5M',
    appId: '1:641995843071:ios:29ab1f309b94b802c9b3ca',
    messagingSenderId: '641995843071',
    projectId: 'mental-health-care-82015',
    storageBucket: 'mental-health-care-82015.firebasestorage.app',
    iosBundleId: 'com.example.mentalHealthcare',
  );
}
