// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4xPodli9tAqrbZUAwcDQaRoOxzILCEL8',
    appId: '1:641995843071:android:7e1701a7b5ad2a73c9b3ca',
    messagingSenderId: '641995843071',
    projectId: 'mental-health-care-82015',
    databaseURL: 'https://mental-health-care-82015-default-rtdb.firebaseio.com',
    storageBucket: 'mental-health-care-82015.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiE5it8w3rSg6GdWfWFQP7dzFO7-G0E5M',
    appId: '1:641995843071:ios:833a35894e4789e0c9b3ca',
    messagingSenderId: '641995843071',
    projectId: 'mental-health-care-82015',
    databaseURL: 'https://mental-health-care-82015-default-rtdb.firebaseio.com',
    storageBucket: 'mental-health-care-82015.firebasestorage.app',
    iosClientId: '641995843071-is2h1hqqpsggd39ht0d7jbdj2t5kvjd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentalHealthcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiE5it8w3rSg6GdWfWFQP7dzFO7-G0E5M',
    appId: '1:641995843071:ios:833a35894e4789e0c9b3ca',
    messagingSenderId: '641995843071',
    projectId: 'mental-health-care-82015',
    databaseURL: 'https://mental-health-care-82015-default-rtdb.firebaseio.com',
    storageBucket: 'mental-health-care-82015.firebasestorage.app',
    iosClientId: '641995843071-is2h1hqqpsggd39ht0d7jbdj2t5kvjd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentalHealthcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcY5bhTK6WoV2mYoMoqJJFe8abTOipM-E',
    appId: '1:641995843071:web:37b4df5604245785c9b3ca',
    messagingSenderId: '641995843071',
    projectId: 'mental-health-care-82015',
    authDomain: 'mental-health-care-82015.firebaseapp.com',
    databaseURL: 'https://mental-health-care-82015-default-rtdb.firebaseio.com',
    storageBucket: 'mental-health-care-82015.firebasestorage.app',
    measurementId: 'G-0ZTHD7XLX7',
  );
}
