// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOZqQ9nV8zaK8rF8bTuBg7RNqFBiwSivU',
    appId: '1:237293095018:web:6c587a91b13fdda1472213',
    messagingSenderId: '237293095018',
    projectId: 'mindassist-256e9',
    authDomain: 'mindassist-256e9.firebaseapp.com',
    databaseURL: 'https://mindassist-256e9-default-rtdb.firebaseio.com',
    storageBucket: 'mindassist-256e9.firebasestorage.app',
    measurementId: 'G-KYEXVZ758W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBPTx25-QFsQuedvF54TLaUTDdrdxjElY',
    appId: '1:237293095018:android:59b4f3611b4614f8472213',
    messagingSenderId: '237293095018',
    projectId: 'mindassist-256e9',
    databaseURL: 'https://mindassist-256e9-default-rtdb.firebaseio.com',
    storageBucket: 'mindassist-256e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY8-IKXowCqN8mGrEhy4YnZpWOEYzQI6o',
    appId: '1:237293095018:ios:592cfb2546096228472213',
    messagingSenderId: '237293095018',
    projectId: 'mindassist-256e9',
    databaseURL: 'https://mindassist-256e9-default-rtdb.firebaseio.com',
    storageBucket: 'mindassist-256e9.firebasestorage.app',
    iosClientId: '237293095018-6f19393eba7ehbhit7rj1ln3bepre2g5.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentalHealthcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY8-IKXowCqN8mGrEhy4YnZpWOEYzQI6o',
    appId: '1:237293095018:ios:592cfb2546096228472213',
    messagingSenderId: '237293095018',
    projectId: 'mindassist-256e9',
    databaseURL: 'https://mindassist-256e9-default-rtdb.firebaseio.com',
    storageBucket: 'mindassist-256e9.firebasestorage.app',
    iosClientId: '237293095018-6f19393eba7ehbhit7rj1ln3bepre2g5.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentalHealthcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOZqQ9nV8zaK8rF8bTuBg7RNqFBiwSivU',
    appId: '1:237293095018:web:6110fbad4b3b1e8c472213',
    messagingSenderId: '237293095018',
    projectId: 'mindassist-256e9',
    authDomain: 'mindassist-256e9.firebaseapp.com',
    databaseURL: 'https://mindassist-256e9-default-rtdb.firebaseio.com',
    storageBucket: 'mindassist-256e9.firebasestorage.app',
    measurementId: 'G-LCVPKWJE87',
  );
}
